apiVersion: v1
kind: PersistentVolume
metadata:
  name: django-nfs-share
spec:
  capacity:
    storage: 1Gi # This size is used to match a volume to a tenents claim
  accessModes:
    - ReadWriteOnce # Access modes are defined below
  persistentVolumeReclaimPolicy: Recycle # Reclaim policies are defined below
  nfs:
    server: 10.200.20.250 # Please change this to your NFS server
    path: /root/share/django # Please change this to the relevant share

